### ISSUE TITLE
Example tests?

### ISSUE THREAD

**Issue by mlmorg** [karma-runner/karma-webdriver-launcher#2]
Sorry to sound like such a n00b but how does one access the `browser` object to actually handle the webdriver? It would be great to have an example of how to write a simple test with this!

Thanks

**Comment by geraldyeo** [comment]
+1
Yes, it will be great to know how to get `browser` in the test suites.

**Comment by LKay** [comment]
+1
Over a year and still no way to access `browser` object?!

**Comment by Fresa** [comment]
I'm not an expert on Karma, but if you are looking for e2e browser automation (i.e. tell the browser what to do within your test) this is not what Karma provides or are built for. You are probably looking for something like Selenium. If I understand it correctly, Karma just executes an html file including your tests and source code using a browser and processes the result. It cannot tell the browser what to do.

I think this thread sums it up pretty good: https://github.com/karma-runner/karma/issues/413
