### ISSUE TITLE
XP configuration

### ISSUE THREAD

**Issue by icvitkovac** [karma-runner/karma-webdriver-launcher#20]
Docs are not OK (at least for me):

  customLaunchers: {
        'IE7': {
          base: 'WebDriver',
          config: webdriverConfig,
          browserName: 'internet explorer',
          platform: 'Windows XP',
          version: '10',
          'x-ua-compatible': 'IE=EmulateIE7',
          name: 'Karma'
        }
      },      

Platform should be XP, and not 'Windows XP'.

**Comment by joeyparrish** [comment]
Selenium sources would seem to confirm this:

https://github.com/SeleniumHQ/selenium/blob/1f2813a8eb6adf51aa7b3ac2f700d4617ff1205e/java/client/src/org/openqa/selenium/Platform.java#L46
