### ISSUE TITLE
Broken due to the disappearance of vargs (Dependency of WD)

### ISSUE THREAD

**Issue by Richard-Walton** [karma-runner/karma-webdriver-launcher#26]
FYI - https://github.com/admc/wd/issues/400

Not sure what you can do about it - But I thought I'd raise awareness.

**Comment by danyshaanan** [comment]
One thing that can be done is to republish vargs with a new name and create a pull request for wd to change the dependency...

**Comment by Richard-Walton** [comment]
WD has dependencies which also use vargs.  Here's to hoping the original author will re-upload the library before we have rename/reupload/change package.json files

**Comment by danyshaanan** [comment]
Yeah, that complicates things...

**Comment by danyshaanan** [comment]
Seems vargs has reappeared. This can be closed now.
