### ISSUE TITLE
Specifying Karma server URL for Android Simulator

### ISSUE THREAD

**Issue by fraserhart** [karma-runner/karma-webdriver-launcher#28]
I'm using Appium with Karma via the karma-webdriver-launcher to run my Jasmine tests on iOS and Android via their respective simulators (mac).

I've been able to configure it correctly to work with iOS but have hit a stumbling block with the android simulator. The Android simulator is launched correctly and it fires up the browser but it tries to hit the Karma server at localhost:9876 where the Karma server is located at 192.168.10.126:9876.

How can I specify the URL to pass to the simulator to open in the browser for testing (in the iOS implementation, there is a safariInitialUrl parameter but there doesn't appear to be an equivalent for Android)

Both the Karma server and Appium server are running on my local machine currently but when this gets deployed, the appium server will be running on a different machine to the Karma server so to be able to specify a URL is important

Here is my config:

var webdriverConfig = {
    hostname: '192.168.10.126',
    port: 4723
}
.

.....
    'Browser-Android' : {
                base: 'WebDriver',
                platformName: "Android",
                deviceName: 'Android',
                config: webdriverConfig,
                browserName: 'Browser',
                platform: 'Android',
                version: '8.4'
            }
........

**Comment by joeyparrish** [comment]
This issue is stale, so I'm declaring issue bankruptcy on these older ones and closing it. If this is still an issue for you, we can reopen or you can open a new one. Sorry this went unanswered for so long!
