### ISSUE TITLE
Is this project is maintained?

### ISSUE THREAD

**Issue by minhyeong-kim** [karma-runner/karma-webdriver-launcher#32]
#23 pendding many times. please check issues.

**Comment by joeyparrish** [comment]
I second this.  Is the project maintained?  Should I be using something else?

**Comment by Havunen** [comment]
Maybe we should create new project

**Comment by johnjbarton** [comment]
I added two collaborators, @joeyparrish and @Havunen

**Comment by Havunen** [comment]
@johnjbarton Thanks, can you add npmjs rights too https://www.npmjs.com/~havunen

**Comment by johnjbarton** [comment]
I'll look in to that; in the meantime open a bug and assign it to me when you are ready to release and I will try it.
