### ISSUE TITLE
"wd" module dependency should be updated to fix Firefox and IE issues

### ISSUE THREAD

**Issue by joeyparrish** [karma-runner/karma-webdriver-launcher#37]
Both geckodriver and IEDriverServer have been upgraded to use the new W3C protocol.  The "wd" module, which "karma-webdriver-launcher" depends on, has just been updated for compatibility with the new protocol.

karma-webdriver-launcher should depend on wd v1.8.0.  If you are using the launcher in the mean time, you can work around this by also depending on wd v1.8.0 directly in your own project.

**Comment by Havunen** [comment]
Updated wd to latest version. Closing! :)
